// Database migration: dump current Supabase public schema (tables, indexes,
// RLS, policies, grants, functions) + data, and optionally push to a target
// Postgres connection string.
//
// Schema introspection runs via a SECURITY DEFINER SQL RPC
// (`admin_exec_sql`) called through supabaseAdmin, so it works in the
// Cloudflare Worker runtime without needing SUPABASE_DB_URL or a raw
// TCP postgres client.
import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireAdmin } from "./admin.middleware";

type Row = Record<string, unknown>;
type DumpOptions = { includeData: boolean; truncate: boolean };

async function runSql(sql: string): Promise<Row[]> {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  const { data, error } = await supabaseAdmin.rpc("admin_exec_sql" as never, { query: sql } as never);
  if (error) throw new Error(`SQL failed: ${error.message}\n--- query ---\n${sql.slice(0, 500)}`);
  return (data as Row[] | null) ?? [];
}

function sqlLit(v: string): string {
  return `'${v.replace(/'/g, "''")}'`;
}

async function buildDumpSql(opts: DumpOptions): Promise<{ sql: string; stats: { tables: number; rows: number; policies: number; functions: number } }> {
  const out: string[] = [];
  const stats = { tables: 0, rows: 0, policies: 0, functions: 0 };

  out.push("-- Generated by admin migration");
  out.push("-- " + new Date().toISOString());
  out.push("SET statement_timeout = 0;");
  out.push("SET client_min_messages = warning;");
  out.push("");

  // Extensions
  const exts = await runSql(`select extname from pg_extension where extname not in ('plpgsql')`);
  for (const e of exts) {
    out.push(`CREATE EXTENSION IF NOT EXISTS "${e.extname}";`);
  }
  if (exts.length) out.push("");

  // Enums
  const enums = await runSql(`
    select t.typname,
           array_agg(e.enumlabel order by e.enumsortorder) as labels
    from pg_type t
    join pg_enum e on e.enumtypid = t.oid
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public'
    group by t.typname
  `);
  for (const en of enums) {
    const labels = (en.labels as string[]).map((l) => sqlLit(l)).join(", ");
    out.push(`DO $$ BEGIN CREATE TYPE public.${en.typname} AS ENUM (${labels}); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
  }
  if (enums.length) out.push("");

  // Functions in public — emit BEFORE tables so column DEFAULTs that call
  // them (e.g. gen_order_no()) resolve when CREATE TABLE runs. Skip our
  // own admin_exec_sql helper since the target db doesn't need it.
  const funcs = await runSql(`
    select p.proname as name, pg_get_functiondef(p.oid) as def
    from pg_proc p
    join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public' and p.proname <> 'admin_exec_sql'
  `);
  stats.functions = funcs.length;
  for (const f of funcs) { out.push(String(f.def) + ";"); out.push(""); }

  // Tables
  const tables = await runSql(`
    select table_name from information_schema.tables
    where table_schema='public' and table_type='BASE TABLE'
    order by table_name
  `);
  stats.tables = tables.length;

  for (const t of tables) {
    const tn = String(t.table_name);
    const cols = await runSql(`
      select column_name, data_type, udt_schema, udt_name, is_nullable, column_default,
             character_maximum_length, numeric_precision, numeric_scale
      from information_schema.columns
      where table_schema='public' and table_name=${sqlLit(tn)}
      order by ordinal_position
    `);
    const pk = await runSql(`
      select kcu.column_name
      from information_schema.table_constraints tc
      join information_schema.key_column_usage kcu
        on kcu.constraint_name=tc.constraint_name and kcu.table_schema=tc.table_schema
      where tc.table_schema='public' and tc.table_name=${sqlLit(tn)} and tc.constraint_type='PRIMARY KEY'
      order by kcu.ordinal_position
    `);

    const colDefs = cols.map((c) => {
      const cAny = c as Row;
      let typ: string;
      const dt = String(cAny.data_type);
      if (dt === "USER-DEFINED") {
        typ = `${cAny.udt_schema}.${cAny.udt_name}`;
      } else if (dt === "ARRAY") {
        typ = `${String(cAny.udt_name).replace(/^_/, "")}[]`;
      } else if (dt === "character varying" && cAny.character_maximum_length) {
        typ = `varchar(${cAny.character_maximum_length})`;
      } else if (dt === "numeric" && cAny.numeric_precision) {
        typ = cAny.numeric_scale != null ? `numeric(${cAny.numeric_precision},${cAny.numeric_scale})` : `numeric(${cAny.numeric_precision})`;
      } else {
        typ = dt;
      }
      let line = `  "${cAny.column_name}" ${typ}`;
      if (cAny.column_default) line += ` DEFAULT ${cAny.column_default}`;
      if (cAny.is_nullable === "NO") line += " NOT NULL";
      return line;
    });
    if (pk.length) {
      colDefs.push(`  PRIMARY KEY (${pk.map((p) => `"${p.column_name}"`).join(", ")})`);
    }
    out.push(`DROP TABLE IF EXISTS public."${tn}" CASCADE;`);
    out.push(`CREATE TABLE public."${tn}" (`);
    out.push(colDefs.join(",\n"));
    out.push(");");
    out.push("");

    // Unique constraints
    const uniques = await runSql(`
      select tc.constraint_name, kcu.column_name, kcu.ordinal_position
      from information_schema.table_constraints tc
      join information_schema.key_column_usage kcu
        on kcu.constraint_name=tc.constraint_name and kcu.table_schema=tc.table_schema
      where tc.table_schema='public' and tc.table_name=${sqlLit(tn)} and tc.constraint_type='UNIQUE'
      order by tc.constraint_name, kcu.ordinal_position
    `);
    const byName = new Map<string, string[]>();
    for (const u of uniques) {
      const arr = byName.get(String(u.constraint_name)) ?? [];
      arr.push(String(u.column_name));
      byName.set(String(u.constraint_name), arr);
    }
    for (const [name, ucols] of byName) {
      out.push(`ALTER TABLE public."${tn}" ADD CONSTRAINT "${name}" UNIQUE (${ucols.map((c) => `"${c}"`).join(", ")});`);
    }

    // Indexes (non-PK/unique)
    const idx = await runSql(`
      select indexname, indexdef from pg_indexes
      where schemaname='public' and tablename=${sqlLit(tn)}
        and indexname not in (
          select conname from pg_constraint where conrelid = 'public."${tn}"'::regclass
        )
    `);
    for (const i of idx) out.push(String(i.indexdef) + ";");
    out.push("");
  }

  // Foreign keys
  const fks = await runSql(`
    select tc.table_name, tc.constraint_name,
           string_agg(kcu.column_name, ',' order by kcu.ordinal_position) as cols,
           ccu.table_schema as ref_schema, ccu.table_name as ref_table,
           string_agg(ccu.column_name, ',' order by kcu.ordinal_position) as ref_cols,
           rc.update_rule, rc.delete_rule
    from information_schema.table_constraints tc
    join information_schema.key_column_usage kcu
      on kcu.constraint_name=tc.constraint_name and kcu.table_schema=tc.table_schema
    join information_schema.constraint_column_usage ccu
      on ccu.constraint_name=tc.constraint_name and ccu.table_schema=tc.table_schema
    join information_schema.referential_constraints rc
      on rc.constraint_name=tc.constraint_name and rc.constraint_schema=tc.table_schema
    where tc.table_schema='public' and tc.constraint_type='FOREIGN KEY'
    group by tc.table_name, tc.constraint_name, ccu.table_schema, ccu.table_name, rc.update_rule, rc.delete_rule
  `);
  for (const f of fks) {
    const cols = String(f.cols).split(",").map((c) => `"${c}"`).join(", ");
    const refCols = String(f.ref_cols).split(",").map((c) => `"${c}"`).join(", ");
    out.push(`ALTER TABLE public."${f.table_name}" ADD CONSTRAINT "${f.constraint_name}" FOREIGN KEY (${cols}) REFERENCES ${f.ref_schema}."${f.ref_table}" (${refCols}) ON UPDATE ${f.update_rule} ON DELETE ${f.delete_rule};`);
  }
  if (fks.length) out.push("");

  // (Functions already emitted before tables.)

  // Triggers
  const trgs = await runSql(`
    select pg_get_triggerdef(t.oid) as def
    from pg_trigger t
    join pg_class c on c.oid=t.tgrelid
    join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='public' and not t.tgisinternal
  `);
  for (const tr of trgs) out.push(String(tr.def) + ";");
  if (trgs.length) out.push("");

  // Grants
  for (const t of tables) {
    const tn = String(t.table_name);
    const grants = await runSql(`
      select grantee, privilege_type from information_schema.role_table_grants
      where table_schema='public' and table_name=${sqlLit(tn)}
        and grantee in ('anon','authenticated','service_role')
    `);
    const byRole = new Map<string, string[]>();
    for (const g of grants) {
      const arr = byRole.get(String(g.grantee)) ?? [];
      arr.push(String(g.privilege_type));
      byRole.set(String(g.grantee), arr);
    }
    for (const [role, privs] of byRole) {
      out.push(`GRANT ${privs.join(", ")} ON public."${tn}" TO ${role};`);
    }
  }
  out.push("");

  // RLS + policies
  const rlsTables = await runSql(`
    select c.relname
    from pg_class c join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='public' and c.relkind='r' and c.relrowsecurity=true
  `);
  for (const t of rlsTables) out.push(`ALTER TABLE public."${t.relname}" ENABLE ROW LEVEL SECURITY;`);
  const policies = await runSql(`
    select schemaname, tablename, policyname, permissive, roles, cmd, qual, with_check
    from pg_policies where schemaname='public'
  `);
  stats.policies = policies.length;
  for (const p of policies) {
    const roles = (p.roles as string[]).join(", ");
    const parts = [
      `CREATE POLICY "${p.policyname}" ON public."${p.tablename}"`,
      `  AS ${p.permissive}`,
      `  FOR ${p.cmd}`,
      `  TO ${roles}`,
    ];
    if (p.qual) parts.push(`  USING (${p.qual})`);
    if (p.with_check) parts.push(`  WITH CHECK (${p.with_check})`);
    out.push(parts.join("\n") + ";");
  }
  if (policies.length) out.push("");

  // Data
  if (opts.includeData) {
    if (opts.truncate && tables.length) {
      out.push("-- truncate first");
      out.push(`TRUNCATE ${tables.map((t) => `public."${t.table_name}"`).join(", ")} RESTART IDENTITY CASCADE;`);
      out.push("");
    }
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    for (const t of tables) {
      const tn = String(t.table_name);
      const { data: rows, error } = await supabaseAdmin.from(tn as never).select("*");
      if (error) throw new Error(`Read ${tn} failed: ${error.message}`);
      const arr = (rows as Row[] | null) ?? [];
      if (!arr.length) continue;
      stats.rows += arr.length;
      const cols = Object.keys(arr[0]);
      const colList = cols.map((c) => `"${c}"`).join(", ");
      for (let i = 0; i < arr.length; i += 200) {
        const batch = arr.slice(i, i + 200);
        const values = batch.map((r) => "(" + cols.map((c) => formatLiteral(r[c])).join(", ") + ")");
        out.push(`INSERT INTO public."${tn}" (${colList}) VALUES`);
        out.push(values.join(",\n") + ";");
      }
      out.push("");
    }
  }

  return { sql: out.join("\n"), stats };
}

function formatLiteral(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number" || typeof v === "bigint") return String(v);
  if (typeof v === "boolean") return v ? "TRUE" : "FALSE";
  if (v instanceof Date) return `'${v.toISOString()}'::timestamptz`;
  if (Array.isArray(v)) {
    const inner = v.map((x) => (x === null ? "NULL" : `"${String(x).replace(/"/g, '\\"')}"`)).join(",");
    return `'{${inner}}'`;
  }
  if (typeof v === "object") {
    return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  }
  return sqlLit(String(v));
}

// ─── Public server functions ─────────────────────────────────────────────

export const adminMigrationDump = createServerFn({ method: "POST" })
  .inputValidator((i: { includeData: boolean; truncate: boolean }) =>
    z.object({ includeData: z.boolean(), truncate: z.boolean() }).parse(i),
  )
  .handler(async ({ data }) => {
    await requireAdmin();
    const { sql, stats } = await buildDumpSql({ includeData: data.includeData, truncate: data.truncate });
    return { sql, stats, sizeKb: Math.round(sql.length / 1024) };
  });

export const adminMigrationRun = createServerFn({ method: "POST" })
  .inputValidator((i: { targetUrl: string; includeData: boolean; truncate: boolean }) =>
    z
      .object({
        targetUrl: z.string().min(20).startsWith("postgres"),
        includeData: z.boolean(),
        truncate: z.boolean(),
      })
      .parse(i),
  )
  .handler(async ({ data }) => {
    await requireAdmin();
    const { sql: dump, stats } = await buildDumpSql({ includeData: data.includeData, truncate: data.truncate });
    let postgres: any;
    try {
      postgres = (await import("postgres")).default;
    } catch {
      throw new Error(
        "当前运行环境不支持直接 TCP Postgres 连接(Cloudflare Worker)。请用「下载 SQL」方式,然后本地跑 psql 导入。",
      );
    }
    const client = postgres(data.targetUrl, { max: 1, idle_timeout: 5, prepare: false, ssl: "require" });
    const startedAt = Date.now();
    try {
      await client.unsafe(dump);
    } catch (e: any) {
      await client.end({ timeout: 5 });
      throw new Error(`Migration failed: ${e?.message ?? String(e)}`);
    }
    await client.end({ timeout: 5 });
    return { ok: true, stats, ms: Date.now() - startedAt, sizeKb: Math.round(dump.length / 1024) };
  });
