/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as AppUsageRouteImport } from './routes/app.usage'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReferralsRouteImport } from './routes/app.referrals'
import { Route as AppRedeemRouteImport } from './routes/app.redeem'
import { Route as AppLogsRouteImport } from './routes/app.logs'
import { Route as AppKeysRouteImport } from './routes/app.keys'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminWebhooksRouteImport } from './routes/admin.webhooks'
import { Route as AdminWebhookLogsRouteImport } from './routes/admin.webhook-logs'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSiteRouteImport } from './routes/admin.site'
import { Route as AdminScriptsRouteImport } from './routes/admin.scripts'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNewapiRouteImport } from './routes/admin.newapi'
import { Route as AdminModelsRouteImport } from './routes/admin.models'
import { Route as AdminMigrationRouteImport } from './routes/admin.migration'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin.email-templates'
import { Route as AdminEmailLogsRouteImport } from './routes/admin.email-logs'
import { Route as AdminEmailCampaignsRouteImport } from './routes/admin.email-campaigns'
import { Route as AdminEmailRouteImport } from './routes/admin.email'
import { Route as AdminDocsRouteImport } from './routes/admin.docs'
import { Route as AdminCompanyRouteImport } from './routes/admin.company'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAffiliatesRouteImport } from './routes/admin.affiliates'
import { Route as ApiPaymentsVerifyRouteImport } from './routes/api/payments/verify'
import { Route as ApiPaymentsCreateRouteImport } from './routes/api/payments/create'
import { Route as ApiPublicPaymentsWebhookWhopRouteImport } from './routes/api/public/payments/webhook/whop'
import { Route as ApiPublicPaymentsWebhookStripeRouteImport } from './routes/api/public/payments/webhook/stripe'
import { Route as ApiPublicPaymentsWebhookEpayRouteImport } from './routes/api/public/payments/webhook/epay'
import { Route as ApiPublicPaymentsWebhookCreemRouteImport } from './routes/api/public/payments/webhook/creem'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppRedeemRoute = AppRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebhookLogsRoute = AdminWebhookLogsRouteImport.update({
  id: '/webhook-logs',
  path: '/webhook-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScriptsRoute = AdminScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewapiRoute = AdminNewapiRouteImport.update({
  id: '/newapi',
  path: '/newapi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMigrationRoute = AdminMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailLogsRoute = AdminEmailLogsRouteImport.update({
  id: '/email-logs',
  path: '/email-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailCampaignsRoute = AdminEmailCampaignsRouteImport.update({
  id: '/email-campaigns',
  path: '/email-campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailRoute = AdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocsRoute = AdminDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompanyRoute = AdminCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAffiliatesRoute = AdminAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPaymentsVerifyRoute = ApiPaymentsVerifyRouteImport.update({
  id: '/api/payments/verify',
  path: '/api/payments/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCreateRoute = ApiPaymentsCreateRouteImport.update({
  id: '/api/payments/create',
  path: '/api/payments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookWhopRoute =
  ApiPublicPaymentsWebhookWhopRouteImport.update({
    id: '/api/public/payments/webhook/whop',
    path: '/api/public/payments/webhook/whop',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookStripeRoute =
  ApiPublicPaymentsWebhookStripeRouteImport.update({
    id: '/api/public/payments/webhook/stripe',
    path: '/api/public/payments/webhook/stripe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookEpayRoute =
  ApiPublicPaymentsWebhookEpayRouteImport.update({
    id: '/api/public/payments/webhook/epay',
    path: '/api/public/payments/webhook/epay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookCreemRoute =
  ApiPublicPaymentsWebhookCreemRouteImport.update({
    id: '/api/public/payments/webhook/creem',
    path: '/api/public/payments/webhook/creem',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/email-campaigns': typeof AdminEmailCampaignsRoute
  '/admin/email-logs': typeof AdminEmailLogsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/newapi': typeof AdminNewapiRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/scripts': typeof AdminScriptsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhook-logs': typeof AdminWebhookLogsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/keys': typeof AppKeysRoute
  '/app/logs': typeof AppLogsRoute
  '/app/redeem': typeof AppRedeemRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/payments/create': typeof ApiPaymentsCreateRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/public/payments/webhook/creem': typeof ApiPublicPaymentsWebhookCreemRoute
  '/api/public/payments/webhook/epay': typeof ApiPublicPaymentsWebhookEpayRoute
  '/api/public/payments/webhook/stripe': typeof ApiPublicPaymentsWebhookStripeRoute
  '/api/public/payments/webhook/whop': typeof ApiPublicPaymentsWebhookWhopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/email-campaigns': typeof AdminEmailCampaignsRoute
  '/admin/email-logs': typeof AdminEmailLogsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/newapi': typeof AdminNewapiRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/scripts': typeof AdminScriptsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhook-logs': typeof AdminWebhookLogsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/keys': typeof AppKeysRoute
  '/app/logs': typeof AppLogsRoute
  '/app/redeem': typeof AppRedeemRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/payments/create': typeof ApiPaymentsCreateRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/public/payments/webhook/creem': typeof ApiPublicPaymentsWebhookCreemRoute
  '/api/public/payments/webhook/epay': typeof ApiPublicPaymentsWebhookEpayRoute
  '/api/public/payments/webhook/stripe': typeof ApiPublicPaymentsWebhookStripeRoute
  '/api/public/payments/webhook/whop': typeof ApiPublicPaymentsWebhookWhopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/email-campaigns': typeof AdminEmailCampaignsRoute
  '/admin/email-logs': typeof AdminEmailLogsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/newapi': typeof AdminNewapiRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/scripts': typeof AdminScriptsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhook-logs': typeof AdminWebhookLogsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/keys': typeof AppKeysRoute
  '/app/logs': typeof AppLogsRoute
  '/app/redeem': typeof AppRedeemRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/payments/create': typeof ApiPaymentsCreateRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/public/payments/webhook/creem': typeof ApiPublicPaymentsWebhookCreemRoute
  '/api/public/payments/webhook/epay': typeof ApiPublicPaymentsWebhookEpayRoute
  '/api/public/payments/webhook/stripe': typeof ApiPublicPaymentsWebhookStripeRoute
  '/api/public/payments/webhook/whop': typeof ApiPublicPaymentsWebhookWhopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/docs'
    | '/forgot-password'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/login'
    | '/models'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/affiliates'
    | '/admin/announcements'
    | '/admin/company'
    | '/admin/docs'
    | '/admin/email'
    | '/admin/email-campaigns'
    | '/admin/email-logs'
    | '/admin/email-templates'
    | '/admin/migration'
    | '/admin/models'
    | '/admin/newapi'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/scripts'
    | '/admin/site'
    | '/admin/users'
    | '/admin/webhook-logs'
    | '/admin/webhooks'
    | '/admin/withdrawals'
    | '/app/billing'
    | '/app/keys'
    | '/app/logs'
    | '/app/redeem'
    | '/app/referrals'
    | '/app/settings'
    | '/app/usage'
    | '/docs/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/admin/'
    | '/app/'
    | '/docs/'
    | '/api/payments/create'
    | '/api/payments/verify'
    | '/api/public/payments/webhook/creem'
    | '/api/public/payments/webhook/epay'
    | '/api/public/payments/webhook/stripe'
    | '/api/public/payments/webhook/whop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/login'
    | '/models'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/affiliates'
    | '/admin/announcements'
    | '/admin/company'
    | '/admin/docs'
    | '/admin/email'
    | '/admin/email-campaigns'
    | '/admin/email-logs'
    | '/admin/email-templates'
    | '/admin/migration'
    | '/admin/models'
    | '/admin/newapi'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/scripts'
    | '/admin/site'
    | '/admin/users'
    | '/admin/webhook-logs'
    | '/admin/webhooks'
    | '/admin/withdrawals'
    | '/app/billing'
    | '/app/keys'
    | '/app/logs'
    | '/app/redeem'
    | '/app/referrals'
    | '/app/settings'
    | '/app/usage'
    | '/docs/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/admin'
    | '/app'
    | '/docs'
    | '/api/payments/create'
    | '/api/payments/verify'
    | '/api/public/payments/webhook/creem'
    | '/api/public/payments/webhook/epay'
    | '/api/public/payments/webhook/stripe'
    | '/api/public/payments/webhook/whop'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/docs'
    | '/forgot-password'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/login'
    | '/models'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/affiliates'
    | '/admin/announcements'
    | '/admin/company'
    | '/admin/docs'
    | '/admin/email'
    | '/admin/email-campaigns'
    | '/admin/email-logs'
    | '/admin/email-templates'
    | '/admin/migration'
    | '/admin/models'
    | '/admin/newapi'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/scripts'
    | '/admin/site'
    | '/admin/users'
    | '/admin/webhook-logs'
    | '/admin/webhooks'
    | '/admin/withdrawals'
    | '/app/billing'
    | '/app/keys'
    | '/app/logs'
    | '/app/redeem'
    | '/app/referrals'
    | '/app/settings'
    | '/app/usage'
    | '/docs/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/admin/'
    | '/app/'
    | '/docs/'
    | '/api/payments/create'
    | '/api/payments/verify'
    | '/api/public/payments/webhook/creem'
    | '/api/public/payments/webhook/epay'
    | '/api/public/payments/webhook/stripe'
    | '/api/public/payments/webhook/whop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiPaymentsCreateRoute: typeof ApiPaymentsCreateRoute
  ApiPaymentsVerifyRoute: typeof ApiPaymentsVerifyRoute
  ApiPublicPaymentsWebhookCreemRoute: typeof ApiPublicPaymentsWebhookCreemRoute
  ApiPublicPaymentsWebhookEpayRoute: typeof ApiPublicPaymentsWebhookEpayRoute
  ApiPublicPaymentsWebhookStripeRoute: typeof ApiPublicPaymentsWebhookStripeRoute
  ApiPublicPaymentsWebhookWhopRoute: typeof ApiPublicPaymentsWebhookWhopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/app/usage': {
      id: '/app/usage'
      path: '/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referrals': {
      id: '/app/referrals'
      path: '/referrals'
      fullPath: '/app/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/redeem': {
      id: '/app/redeem'
      path: '/redeem'
      fullPath: '/app/redeem'
      preLoaderRoute: typeof AppRedeemRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/keys': {
      id: '/app/keys'
      path: '/keys'
      fullPath: '/app/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/webhook-logs': {
      id: '/admin/webhook-logs'
      path: '/webhook-logs'
      fullPath: '/admin/webhook-logs'
      preLoaderRoute: typeof AdminWebhookLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scripts': {
      id: '/admin/scripts'
      path: '/scripts'
      fullPath: '/admin/scripts'
      preLoaderRoute: typeof AdminScriptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newapi': {
      id: '/admin/newapi'
      path: '/newapi'
      fullPath: '/admin/newapi'
      preLoaderRoute: typeof AdminNewapiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/migration': {
      id: '/admin/migration'
      path: '/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AdminMigrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-logs': {
      id: '/admin/email-logs'
      path: '/email-logs'
      fullPath: '/admin/email-logs'
      preLoaderRoute: typeof AdminEmailLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-campaigns': {
      id: '/admin/email-campaigns'
      path: '/email-campaigns'
      fullPath: '/admin/email-campaigns'
      preLoaderRoute: typeof AdminEmailCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email': {
      id: '/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AdminEmailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/docs': {
      id: '/admin/docs'
      path: '/docs'
      fullPath: '/admin/docs'
      preLoaderRoute: typeof AdminDocsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/company': {
      id: '/admin/company'
      path: '/company'
      fullPath: '/admin/company'
      preLoaderRoute: typeof AdminCompanyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/affiliates': {
      id: '/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAffiliatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/payments/verify': {
      id: '/api/payments/verify'
      path: '/api/payments/verify'
      fullPath: '/api/payments/verify'
      preLoaderRoute: typeof ApiPaymentsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/create': {
      id: '/api/payments/create'
      path: '/api/payments/create'
      fullPath: '/api/payments/create'
      preLoaderRoute: typeof ApiPaymentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook/whop': {
      id: '/api/public/payments/webhook/whop'
      path: '/api/public/payments/webhook/whop'
      fullPath: '/api/public/payments/webhook/whop'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookWhopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook/stripe': {
      id: '/api/public/payments/webhook/stripe'
      path: '/api/public/payments/webhook/stripe'
      fullPath: '/api/public/payments/webhook/stripe'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook/epay': {
      id: '/api/public/payments/webhook/epay'
      path: '/api/public/payments/webhook/epay'
      fullPath: '/api/public/payments/webhook/epay'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookEpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook/creem': {
      id: '/api/public/payments/webhook/creem'
      path: '/api/public/payments/webhook/creem'
      fullPath: '/api/public/payments/webhook/creem'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookCreemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAffiliatesRoute: typeof AdminAffiliatesRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCompanyRoute: typeof AdminCompanyRoute
  AdminDocsRoute: typeof AdminDocsRoute
  AdminEmailRoute: typeof AdminEmailRoute
  AdminEmailCampaignsRoute: typeof AdminEmailCampaignsRoute
  AdminEmailLogsRoute: typeof AdminEmailLogsRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminMigrationRoute: typeof AdminMigrationRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminNewapiRoute: typeof AdminNewapiRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminScriptsRoute: typeof AdminScriptsRoute
  AdminSiteRoute: typeof AdminSiteRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebhookLogsRoute: typeof AdminWebhookLogsRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAffiliatesRoute: AdminAffiliatesRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCompanyRoute: AdminCompanyRoute,
  AdminDocsRoute: AdminDocsRoute,
  AdminEmailRoute: AdminEmailRoute,
  AdminEmailCampaignsRoute: AdminEmailCampaignsRoute,
  AdminEmailLogsRoute: AdminEmailLogsRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminMigrationRoute: AdminMigrationRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminNewapiRoute: AdminNewapiRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminScriptsRoute: AdminScriptsRoute,
  AdminSiteRoute: AdminSiteRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebhookLogsRoute: AdminWebhookLogsRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppKeysRoute: typeof AppKeysRoute
  AppLogsRoute: typeof AppLogsRoute
  AppRedeemRoute: typeof AppRedeemRoute
  AppReferralsRoute: typeof AppReferralsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppKeysRoute: AppKeysRoute,
  AppLogsRoute: AppLogsRoute,
  AppRedeemRoute: AppRedeemRoute,
  AppReferralsRoute: AppReferralsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsageRoute: AppUsageRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiPaymentsCreateRoute: ApiPaymentsCreateRoute,
  ApiPaymentsVerifyRoute: ApiPaymentsVerifyRoute,
  ApiPublicPaymentsWebhookCreemRoute: ApiPublicPaymentsWebhookCreemRoute,
  ApiPublicPaymentsWebhookEpayRoute: ApiPublicPaymentsWebhookEpayRoute,
  ApiPublicPaymentsWebhookStripeRoute: ApiPublicPaymentsWebhookStripeRoute,
  ApiPublicPaymentsWebhookWhopRoute: ApiPublicPaymentsWebhookWhopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
